# Generated by Django 3.0.7 on 2020-07-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200722_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
    ]
