# Generated by Django 3.0.7 on 2020-07-22 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200722_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='leads.Lead'),
        ),
    ]
